README.md, example/pubspec.lock, lib/flutter_calendar_carousel.dart, pubspec.lock, pubspec.yaml
Added one optional parameter: **`weekFormat`**
It accepts a boolean argument and decides whether to use the week-only format or the regular calendar. Defaults to `FALSE`.
Layout is copied over from [apptreesoftware/flutter_calendar](https://github.com/apptreesoftware/flutter_calendar), but without the expandable full-size calendar. The right-side button lets the user selected a date to display its week. The left-side button jumps to the current date (today).
Otherwise the styling options, callback handling etc have not been changed.
=> Week only page (#1)

README.md, example/pubspec.lock, lib/flutter_calendar_carousel.dart, pubspec.lock, pubspec.yaml
Added one optional parameter: weekFormat
It accepts a boolean argument and decides whether to use the week-only format or the regular calendar. Defaults to FALSE.
Layout is copied over from apptreesoftware/flutter_calendar, but without the expandable full-size calendar. The right-side button lets the user selected a date to display its week. The left-side button jumps to the current date (today).
Otherwise the styling options, callback handling etc have not been changed.
Closes (#1).
=> Week-only format

lib/flutter_calendar_carousel.dart
I needed this parameter to disable vertical scrolling of the grid. Horizontal scroll still works fine.
=> add custom physics parameter

lib/flutter_calendar_carousel.dart
This PR should add the right first day of the week based on the locale parameter.
It removes statically specified weekdays and get them from intl.
It uses a locale parameter to better suit all purposes (forced language, one from a configuration file or auto detecting it)
Colors for Week-end are applied correctly according to the locale.
Has been tested on some languages (en, ru and fr), need further testing before any merging.
=> Better localization support

lib/flutter_calendar_carousel.dart
- Fixed a FlatButton to use selectedDayButtonColor instead of selectedDayBorderColor as its fill color
- Added a conditional to render the border of the FlatButton when isSelectedDay is true
=> Fixed FlatButton fill and border color

example/pubspec.lock, lib/flutter_calendar_carousel.dart
prevDaysTextStyle and nextDaysTextStyle overwriting weekendTextStyle
[check this issue](https://github.com/dooboolab/flutter_calendar_carousel/issues/41)
=> Fix weekend days text style

lib/flutter_calendar_carousel.dart
I added `headerTitleTouchable` and `onHeaderTitlePressed` props. 
By default `headerTitleTouchable`  is set to `false`, so `headerTitle` will not react on tap while you don't change it to `true`.
If `headerTitleTouchable` is provided, but there is no `onHeaderTitlePressed` prop then it works like now (calling native calendar view).
If `headerTitleTouchable` is true, and `onHeaderTitlePressed` provided (it should be void? function), then tap on `headerTitle` calls `onHeaderTitlePressed` function.
=> headerTitleTouchable and onHeaderTitlePressed props added

lib/flutter_calendar_carousel.dart, lib/src/default_styles.dart, lib/src/src.dart
Moved out text styles to their own file, also changed from final to const. There's no need to assign them at runtime as they don't change. with const they will be assigned at compile time
as discussed in #67
=> [WIP] Refactoring - Move out default styles

lib/flutter_calendar_carousel.dart
Dot icon per event:
````
var mark_icon = Container(
margin: EdgeInsets.symmetric(horizontal: 1.0),
color: Colors.yellow,
height: 4.0,
width: 4.0,
);
var event =  new Event(
date: date,
title: 'title'
icon: mark_icon,
);
````
In calendar init:
````
markedDateShowIcon: false,
markedDateIconBuilder: (event) {
return event.icon;
},
````
=> Setting dot icon per event

lib/flutter_calendar_carousel.dart, lib/src/weekday_row.dart, test/src/weekday_row_test.dart
As discussed in #67
@hyochan I'm not sure about your comment `When FIRSTDAYOFWEEK is 0 in dart-intl, it represents Monday.` but I found that when using weekdays from `dateSymbols` Sunday is the first day, you can check it out [here](https://github.com/dart-lang/intl/blob/461bea33a0ad336b29739a27f0e6e29546bd1718/lib/date_symbols.dart#L298) 
So I went ahead and omitted using `firstDayOfWeek` like you were previously doing.
=> [WIP] Refactoring - Separate and Test Weekdays row

lib/flutter_calendar_carousel.dart
Hi,
Currently, I see that when the calendar is in week format, the input date of onCalendarChanged is unchanged even when we navigate to the weeks of different month. This PR is to pass the first date of week to onCalendarChanged when we navigate between the weeks in week view.
Please help to take a look and see that if my proposed fix is correct.
Thanks,
Duy
=> Pass first date of week to onCalendarChanged in week view

README.md, lib/flutter_calendar_carousel.dart
Added a way to provide custom build function for days. All properties like circle border are also applied to custom day container. Text style is also sent into the builder, if user provided one in Calendar's properties suitable for current day. If user didn't provide any, default text style is sent into user's build function.
If user's build function returns null, default container method is called, which gives user an opportunity to provide build function only for a specific day, leaving rest as default.
=> Custom day container feature.

lib/classes/event.dart, lib/flutter_calendar_carousel.dart
I created an interface with the methods to get the default fields of the event class and implemented it.
I then changed each occurrence of Event class with T class that extends the interface.
This will allow us to make the plugin work with any custom class (as I already do in some of my projects).
Of course with the default Event class it will continue to work because it implements EventInterface.
=> Allow the use of generic type with Interface

lib/flutter_calendar_carousel.dart
Resolve #175 
Fixed using header arrow button when trying to go out of range.
In addition, when ```weekFormat: true```, the problem that cannot be displayed until ```maxSelectedDate``` was corrected.
=> fix header_arrow button onPressed

lib/flutter_calendar_carousel.dart
bug fix: #178 
An error occurred because no default was set for the upper and lower dates.
```minSelectedDate``` is set to 1960,
```maxSelectedDate``` is set to 30 years from the day.
=> Bug fix: minSelectedDate is null by default. #178

lib/flutter_calendar_carousel.dart
bug fix: #192 
_startWeekday, _endWeekday need refresh before pageControl itemBuild
=> Fix Calendar displays incorrectly when scrolling horizontally

pubspec.yaml
flutter_calendar_carousel doesn't work with the new Flutter beta any more:
```
Because flutter_calendar_carousel 1.5.1 depends on intl >=0.1.0 <0.17.0 and no versions of flutter_calendar_carousel match >1.5.1 <2.0.0, flutter_calendar_carousel ^1.5.1 requires intl >=0.1.0 <0.17.0.
So, because (app name) depends on both flutter_calendar_carousel ^1.5.1 and intl ^0.17.0-nullsafety.2, version solving failed.
pub get failed (1; So, because (app name) depends on both flutter_calendar_carousel ^1.5.1 and intl ^0.17.0-nullsafety.2, version solving failed.)
exit code 1
```
Since the last intl version 0.16.1 only sdk constraints were changed, so it should be safe to support 0.17.x:
https://github.com/dart-lang/intl/commits/master
FYI if one does not update intl with Flutter beta, you get this …
=> Update intl dependency

lib/flutter_calendar_carousel.dart
Allow customDayBuilder and markedDateIconBuilder to return null. If it
returns null, use the default. This restores the original behavior from
v1. Fixes #260.
=> Null safety improvements

lib/flutter_calendar_carousel.dart
The class 'WidgetsBinding' cannot be null. Try replacing '?.' with '.'
=> fix: flutter 3.0 upgrade

lib/flutter_calendar_carousel.dart
Inactive days were still clickable, despite being disabled. They had an InkWell (Material Ripple) animation as well
This PR fixes this
=> Fix inactive (disabled) days being clickable

lib/flutter_calendar_carousel.dart
Non-breaking change
Adds support for an optional parameter `daysBorderRadius`, which allows the user to configure a custom border radius for days
If `daysHaveCircularBorder = true`, the property is ignored
=> Add ability to configure day border radius by setting `daysBorderRadius`
