hyochan/flutter_calendar_carousel

- README.md
Used raw.githubusercontent.com instead of github.com domain so that pub could display them.
> Fix broken images on pub

- README.md
- lib/flutter_calendar_carousel.dart
Hello, 
I really appreciate the work you've put into this project as it has helped me immensely. I did find however that there was not an easy way to change the color of the header text. 
What do you think about adding a headerTextStyle variable like I have shown in my code? It is the easiest method I have found to modify the style of the header while keeping the default date format.
Thanks,
- Chris Soliday
> Implemented a way to change the header text style

- lib/flutter_calendar_carousel.dart
https://github.com/dooboolab/flutter_calendar_carousel/issues/6
My only worry would be performance issues mapping over a long long list
> Mark dates with non-zero times.

- README.md
- example/pubspec.lock
- lib/flutter_calendar_carousel.dart
- pubspec.lock
- pubspec.yaml
Reverts dooboolab/flutter_calendar_carousel#10
> Revert "Week only page (#1)"

- lib/flutter_calendar_carousel.dart
Small fix for the order weeks are displayed. Only fixes half of the issues on #15. 
I'm still investigating the second issue (borders), will push another PR when I fix it.
> Fixed order of weeks (#15)

- lib/flutter_calendar_carousel.dart
I'm just notice that the weekdays become missing even if I set the 'showWeekDays' true. And the other issue is the weekdays just showing from sunday to friday, no saturday. 
Thanks
> weekdays bug fixing

- README.md
- example/lib/main.dart
- lib/classes/events.dart
- lib/flutter_calendar_carousel.dart
As discussed last night, I've update the event list and added Events class.
> Mapping Events for Better Performance

- example/lib/main.dart
- lib/classes/event.dart
- lib/classes/event_list.dart
> EventList bug fixing

- README.md
headerTitleTouchable and onHeaderTitlePressed props added to README.md
> headerTitleTouchable, onHeaderTitlePressed added

- README.md
- lib/flutter_calendar_carousel.dart
Add property for static six week format to keep calendar height consistent between months.
> Add property for static six week format

- lib/flutter_calendar_carousel.dart
- lib/src/weekday_row.dart
- test/src/weekday_row_test.dart
I just reused the old code to fix issues people are having, I'll take a look more in detail when I have time.
this fixes both #79 and #80
> fix #79 and #80

- lib/flutter_calendar_carousel.dart
changed an import to part so that EventList class could be accessed by library user.
> updated flutter_calendar_carousel.dart

- CHANGELOG.md
- README.md
- example/pubspec.lock
- lib/flutter_calendar_carousel.dart
- pubspec.lock
- pubspec.yaml
Resolve #107
use `showOnlyCurrentMonthDate` to only show current month's date.
> Add feature request for #107

- CHANGELOG.md
- lib/flutter_calendar_carousel.dart
- pubspec.yaml
Fix handling vertical scroll animation depended on customGridViewPhysics widget param.
> Fix vertical scroll behavior for weekFormat calendar view

- lib/flutter_calendar_carousel.dart
It would be nice if you can enable page snapping from the constructor. Swiping on the week view can sometimes only scroll halfway.
Awesome package btw :)
> Added option for page snapping to be optional

- lib/flutter_calendar_carousel.dart
After testing my latest commit have found a little problem with textstyle, where it didn't merge with the TextStyle of the theme of user's app. This commit fixes that problem.
> Custom day builder bug fix.

- lib/flutter_calendar_carousel.dart
- lib/src/weekday_row.dart
Custom weekday builder now gets weekday int number (user got only a weekday string before, so it was hard to determine which weekday to build). 
Added doc to WeekdayBuilder.
> Added doc to custom weekday builder. Weekday number is now supplied to the builder.

- lib/flutter_calendar_carousel.dart
Resolve #123 
the Duration of the start date must be from 0.
But List<int>.generate function generate integer 1 to 7.
> Fixed Week view and month view show not the same  dates and days.(#123)

- lib/flutter_calendar_carousel.dart
Now we can set the scroll direction with Axis.horizontal (default value) or Axis.vertical.
> Added option for set scrollDirection (horizontal or vertical)

- lib/flutter_calendar_carousel.dart
Add upper and lower date limits.
> add custom month range #161

- CHANGELOG.md
- README.md
- example/pubspec.lock
- lib/flutter_calendar_carousel.dart
- pubspec.yaml
- To support #173, created `pageScrollPhysics`.
> enhace: Expose `scrollPhysics` for page builder

- example/lib/main.dart
- lib/flutter_calendar_carousel.dart
The display date can be specified externally.
This enables custom headers.
> Target date for custom header

- lib/flutter_calendar_carousel.dart
add props for onLeftButtonPressed and onRightButtonPressed
> add props for onLeftButtonPressed onRightButtonPressed

- lib/flutter_calendar_carousel.dart
When try to switch to another month with HeaderButton got the error - "The method 'call' was called on null."
> [Bugfix]- When switch month error - "The method 'call' was called on null."

- example/pubspec.lock
- lib/classes/event.dart
- pubspec.lock
I have added an additional field to the event model to keep each event unique, because the event name can be similar, even the dates can be similar but we needed something to make it unique, the id will be used to keep track of all the events and fetching events from the database
I have created the issue and fixed it as well #256
> updated event model and added event id

- lib/classes/event.dart
Additional fields in the event class mean that developers can create more interactive designs for their event lists and tailor their data even better to reflect the identity of the app they are developing.
Fields added include:
- A description field so that users can add additional text about an event.
- A location field in case the developer wants to highlight the location of an event.
> feat: Added extra fields in the Event class

- .github/workflows/ci.yml
- lib/classes/marked_date.dart
- lib/flutter_calendar_carousel.dart
> migrate with new flutter version  3.0.0

- example/android/app/src/main/AndroidManifest.xml
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- example/ios/Runner/Info.plist
> upgrade android embedding v2

- lib/flutter_calendar_carousel.dart
Since the change from FlatButtons to TextButtons buttonColors (like selectedDayButtonColor) cannot be adjusted. Just nothing happens. This fix works for me.
> fix: buttonColors

- example/pubspec.yaml
- pubspec.yaml
Hello. I change the version of the intl package from 0.18.0 to 0.19.0 to solve the compilation problem in the new stable version of flutter 3.22.0
> intl 0.19.0

- pubspec.yaml
> Update pubspec.yaml update intl packege use latest

- example/ios/Runner.xcodeproj/project.pbxproj
- lib/flutter_calendar_carousel.dart
maxDot parameter of type integer was added to specify the maximum dots allowed.
> Added a maxDot parameter

- pubspec.yaml
> version Changed

- example/analysis_options.yaml
- example/lib/main.dart
- example/pubspec.lock
- example/pubspec.yaml
- example/test/widget_test.dart
Edits taken directly from respectable migration guides, and from the latest Flutter app template: 
```sh
flutter create -t app --platforms=android,ios -i objc -a java --org com.dooboolab example
```
Plugin's source code was not altered. The example was just migrated to the latest Flutter template.
> chore: upgrade dependencies & add linter

- lib/flutter_calendar_carousel.dart
> Don't invoke `animateToPage` when page was scrolled manually

- lib/flutter_calendar_carousel.dart
Non-breaking change. Code style improvement
> Replace bare Function types with typedefs
